### ISSUE TITLE
Code for adding map legend

### ISSUE THREAD

**Issue by AdamRJensen** [williamhobbs/solar-fleet-forecast-probability-tool#5]
Code for adding map legend to the map in this [notebook](https://github.com/williamhobbs/solar-fleet-forecast-probability-tool/blob/main/02_solar_power_forecasts.ipynb).

        fig = plt.figure(figsize=(6, 6))
        
        ax = fig.add_subplot(1,1,1, projection=ccrs.PlateCarree())
        
        resolution = '50m'
        
        ax.add_feature(cfeature.LAND.with_scale(resolution), facecolor='lightgrey', zorder=0)
        ax.add_feature(cfeature.STATES.with_scale(resolution), facecolor='none', edgecolor='black', lw=0.1, zorder=0)
        ax.coastlines(resolution=resolution, edgecolor='black', lw=0.4)
        
        # ax.set_extent([-95, -79, 24, 38])
        ax.set_extent([-91, -80.5, 27, 35.5])
        
        marker_scaling = 2
        
        params = {'color': 'red', 'edgecolors': 'black', 'alpha': 0.6}
        
        plt.scatter(x=plants_df.longitude, y=plants_df.latitude,
                    s=plants_df.ac_capacity*marker_scaling,
                    transform=ccrs.PlateCarree(),
                    **params
        )
        
        for size in [20, 100, 200]:
            plt.scatter(0, 0, s=size*marker_scaling, transform=ccrs.PlateCarree(), **params, label=size)
        
        ax.legend(loc='lower left', title='Plant size [MW]', frameon=False, ncol=3,
                  borderaxespad=1, labelspacing=1, columnspacing=0.5, handletextpad=0.3)
        
        # plt.savefig("site_map.png", dpi=150, bbox_inches='tight') # <-- uncomment this to save the image
        plt.show()

**Comment by williamhobbs** [comment]
Done. Thanks @AdamRJensen! I gave you a shout-out for this during my talk

(I pushed the commit while on an airplane. It's the future! ✈️)
